### ISSUE TITLE
Further Examples

### ISSUE THREAD

**Issue by Creekie1337** [timlebrun/node-icecast-server#1]
Hi,

It'd be useful to have more examples, I believe I've figured out how to stream to the server however I don't see any way to actually access it like a live internet radio. Is this even possible with this?

I appreciate the help :)

**Comment by Text-only** [comment]
**Automatically,generated**

- [ ] Pre-programmed
- [ ] Premise
- [ ] Phase
- [ ] Allocation
is database multiple clouds...|
..maybe if the data is on-line.

**Comment by alexandrucancescu** [comment]
@Creekie1337 Looking at the code there is no logic to handle serving the listeners/clients part, only ingesting the stream and reading metadata. Besides reading the metadata from the audio stream the code seems to be completely ignoring the audio stream. I think this repo is a work in progress and not a working Icecast server.

**Comment by timlebrun** [comment]
Heya ! Can confirm indeed this was a work in progress at the time.

I'm pretty sure the whole thing was working at the time, and the main example I was using is in the `src/test.ts` file.

Please note that was meant to be an Icecast server _library_ (in an "express" way) to be integrated in an external projet (which then handles the events emitted from the received data), and not a fully fledged Icecast system !
